# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-09 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='user',
            new_name='uploader',
        ),
    ]
