# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-24 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20180410_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travelDateFrom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travelDateTo',
            field=models.CharField(max_length=255),
        ),
    ]
