# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-24 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180409_1922'),
        ('travel', '0004_auto_20180424_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='allusers',
            new_name='travelers',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='uploader',
        ),
        migrations.AddField(
            model_name='trip',
            name='planner',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='plannedTrips', to='login.User'),
            preserve_default=False,
        ),
    ]
